[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.28"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "foundry-out"}]

[profile.ci.fuzz]
runs = 10_000
