[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.28"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "foundry-out"}]

[profile.ci.fuzz]
runs = 10_000
